version: '3.1'
services:
    api-gw:
        container_name: 23p-api-lab
        restart: always
        ports:
            - 8000:8000
        image: 23p-api-lab:latest
        command: ["python3", "/opt/main.py"]