apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: p23
  name: p23
  namespace: default
spec:
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: p23
  template:
    metadata:
      labels:
        app: p23
    spec:
      
      containers:
      - image: us.gcr.io/alien-bruin-284822/23p-api-lab:latest
        imagePullPolicy: Always
        name: 23p-api-lab
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
