apiVersion: v1
kind: Service
metadata:
  labels:
    app: p23
  name: p23
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: p23
  sessionAffinity: None
  type: ClusterIP

